service:
  main:
    type: LoadBalancer
    loadBalancerIP: 10.1.5.198
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    type: LoadBalancer
    loadBalancerIP: 10.1.5.198
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575

mcbackup:
  enabled: true
  initial_delay: 2m
  backup_interval: 1h
  player_online_check_interval: 10m
  prune_backups_days: 7
  pause_if_no_players: true
  link_latest: false
  # values gzip,bzip2,zstd
  tar_compress_method: gzip
  # White spaced separated list
  zstd_params:
    - --long=25
    - --single-thread
  # comma separated list
  excludes:
    - "*.jar"
    - "cache"
    - "logs"
    - "*.tmp"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            #SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            #QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            #RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on Matt's Homelab!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 8192M
            RCON_PASSWORD: "HardcodedPasswords!"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: "willardbug, killbilljill, throwdownn64"
            # OPS: ""
            # ICON: ""
            SEED: "5063885805507972583"
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM
  mcbackup:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        mcbackup:
          primary: true
          enabled: true
          imageSelector: mcBackupImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          #env:
          #  BACKUP_METHOD: "tar"
          #  DEST_DIR: "{{.Values.persistence.backups.mountPath }}"
          #  SRC_DIR: "{{.Values.persistence.data.mountPath }}"
          #  SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
          #  RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
          #  RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
          #  RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
          #  INITIAL_DELAY: "{{ .Values.mcbackup.initial_delay }}"
          #  BACKUP_INTERVAL: "{{ .Values.mcbackup.backup_interval }}"
          #  PRUNE_BACKUPS_DAYS: "{{ .Values.mcbackup.prune_backups_days }}"
          #  PAUSE_IF_NO_PLAYERS: "{{ .Values.mcbackup.pause_if_no_players }}"
          #  PLAYERS_ONLINE_CHECK_INTERVAL: "{{ .Values.mcbackup.player_online_check_interval }}"
          #  LINK_LATEST: "{{ .Values.mcbackup.link_latest }}"
          #  TAR_COMPRESS_METHOD: "{{ .Values.mcbackup.tar_compress_method }}"
          #  ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
          #  EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'

persistence:
  data:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /mnt/nvmes/Apps/game_servers_data/minecraft/data
      mcbackup:
        mcbackup:
          mountPath: /mnt/nvmes/Apps/game_servers_data/minecraft/data
          readOnly: true
  backups:
    enabled: true
    targetSelector:
      mcbackup:
        mcbackup:
          mountPath: /mnt/nvmes/Apps/game_servers_data/minecraft/backups
