service:
  main:
    type: LoadBalancer
    loadBalancerIP: 10.1.5.201
    ports:
      main:
        protocol: udp
        port: 19876
        targetPort: 19876
  query:
    type: LoadBalancer
    loadBalancerIP: 10.1.5.201
    enabled: true
    ports:
      query:
        enabled: true
        port: 19877
        protocol: udp
        targetPort: 19877
persistence:
  serverfiles:
    enabled: true
    type: nfs
    mountPath: /serverdata/serverfiles
    path: /mnt/nvmes/Apps/game_servers_data/v-rising/serverdata/serverfiles
    server: 10.1.5.11
  steamcmd:
    enabled: true
    type: nfs
    mountPath: /serverdata/steamcmd
    path: /mnt/nvmes/Apps/game_servers_data/v-rising/serverdata/steamcmd
    server: 10.1.5.11

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            #Steam settings
            ENABLE_BEPINEX: "false"
            GAME_ID: "1829350"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
            #V Rising settings
            VR_SERVER_NAME: "V Rising Blood and Iron"
            VR_DESCRIPTION: "Blood and Iron!"
            WORLD_NAME: "world1"
            VR_GAME_PORT: 19876
            VR_QUERY_PORT: 19877
            VR_FPS: 120
            VR_LOWER_FPS_WHEN_EMPTY: true
            VR_LOWER_FPS_WHEN_EMPTY_VALUE: 5
            VR_PASSWORD: Sephi101ForLife!
            VR_LIST_ON_EOS: false
            VR_LIST_ON_STEAM: false

            #Game Setting Presets, with added overrides later: Added overrides didn't work
            #VR_PRESET: "StandardPvE"
            #VR_DIFFICULTY_PRESET: Difficulty_Normal
            VR_SAVE_COUNT: 100
            VR_SAVE_INTERVAL: 60
            VR_AUTOSAVESMARTKEEP: 10:10:1,20:2:1,30:4:1,60:2:1,120:2:1,240:2:1,480:2:1,960:2:1,1440:3:2,2880:1:1,4320:1:1,5760:0:1,7200:0:1,8640:0:1,10080:0:1,11520:0:1,12960:0:1,14400:0:1,201600:14:1

          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
